config/routes.rb
Rails.application.routes.draw do
  get 'items/create'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'lists#index'

  resources :lists do
    resources :items
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :list
  validates :description, presence: true

  def complete?
    self.status == 1
  end

  def incomplete?
    self.status == 0
  end
end

app/models/list.rb
class List < ApplicationRecord
  has_many :items
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def create
    @list = List.find(params[:list_id])
    @item = @list.items.new(item_params)
    if @item.save
      redirect_to list_path(@list)
    else
      @items = @list.items.reverse
      render "lists/show"
    end
  end

  def update
    @item = Item.find(params[:id])
    @item.update(item_params)
    redirect_to list_path(@item.list)
  end

  def destroy
    @item = Item.find(params[:id])
    @item.destroy
    redirect_to list_path(@item.list)
  end

  private

  def item_params
    params.require(:item).permit(:description, :status)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all.reverse
    @list = List.new
  end

  def show
    @list = List.find_by(id: params[:id])
    @items = @list.items.reverse
    @item = Item.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_url(@list)
    else
      @lists = List.all.reverse
      render :index
    end
  end

  private

  def list_params
    params.require(:list).permit(:name)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
  def li_class_for_item(item)
    "completed" if item.complete?
  end

  def li_for_item(item)
    content_tag_for :li, item, class: li_class_for_item(item) do
      yield
    end
  end

  def form_for_item_status(item)
    form_for([item.list, item]) do |f|
      f.check_box :status, class: "toggle", checked: item.complete?
    end
  end
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/items/_item_li.html.erb
<%= li_for_item(item) do %>
  <div class="view">
    <%= form_for_item_status(item) %>
    <label><%= item.description %></label>
    <%= button_to "x", list_item_path(item.list, item), method: :delete, :class => "destroy" %>
  </div>
<% end %>

app/views/items/create.html.erb
<h1>Items#create</h1>
<p>Find me in app/views/items/create.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoMvc</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<section class="todoapp">
			<header class="header">
				<h1>TODO lists</h1>
				<!-- <input class="new-todo" placeholder="Make new list" autofocus=""> -->
				<%= form_for(@list) do |f| %>
					<%= f.text_field :name, :class => "new-todo", :placeholder => (@list.errors.full_messages_for(:name).first || "New list...") %>
					<%= f.submit :style => 'display: none' %>
				<% end %>
			</header>
			<section class="main">
				<ul class="todo-list">
          <% @lists.each do |list| %>
          <li>
            <div class="view">
              <label><%= link_to list.name, list_path(list) %></a></label>
            </div>
          </li>
          <% end %>
        </ul>
			</section>
			<footer class="footer" style="display: none;">

			</footer>
		</section>

app/views/lists/show.html.erb
<section class="todoapp">
			<header class="header">
				<h1><%= @list.name %></h1>
				<%= form_for([@list, @item]) do |f| %>
				<%= f.text_field :description, :class => "new-todo", :placeholder => (@item.errors.full_messages_for(:description).first || "Add item...") %>
					<%= f.submit :style => 'display: none' %>
				<% end %>
			</header>
			<section class="main">
				<ul class="todo-list">
					<%= render collection: @items, partial: "items/item_li", as: :item %>
        </ul>
			</section>
			<footer class="footer" style="display: none;">

			</footer>
		</section>